- 23_11_week4/donghyun/12891.cpp
- 23_11_week4/donghyun/19583.cpp
- 23_11_week4/donghyun/3663.cpp
- 23_11_week4/donghyun/4375.cpp
- 23_11_week4/donghyun/9009.cpp
> 23_11_week4 동현 완료

- 23_11_week4/jahoon/boj12891.cpp
- 23_11_week4/jahoon/boj19583.cpp
- 23_11_week4/jahoon/boj3663.cpp
- 23_11_week4/jahoon/boj4375.cpp
- 23_11_week4/jahoon/boj9009.cpp
- 23_11_week4 문제 완료
- [boj12891](https://velog.io/@aoleejohn/C-boj-12891-DNA-%EB%B9%84%EB%B0%80%EB%B2%88%ED%98%B8)
- [boj19583](https://velog.io/@aoleejohn/C-boj-19583-%EC%8B%B8%EC%9D%B4%EB%B2%84%EA%B0%9C%EA%B0%95%EC%B4%9D%ED%9A%8C)
- [boj3663](https://velog.io/@aoleejohn/C-boj-3663-%EA%B3%A0%EB%93%9D%EC%A0%90)
- [boj4375](https://velog.io/@aoleejohn/C-boj-4375-1)
- [boj9009](https://velog.io/@aoleejohn/C-boj-9009-%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98)
> 23_11_week4 자훈 완료

- 23_11_week4/jiyeon/12891.cpp
- 23_11_week4/jiyeon/19583.cpp
- 23_11_week4/jiyeon/4375.cpp
- 23_11_week4/jiyeon/9009.cpp
아래 두 문제는 계속 시간 초과가 나서 검색을 통해 해결했습니다.
- 4575번: 1 (mod 연산)
- 12891번: DNA 비밀번호 (슬라이딩 윈도우 알고리즘)
> 23_11_week4 지연 완료

- 23_11_week5/donghyun/1013.cpp
- 23_11_week5/donghyun/1025.cpp
- 23_11_week5/donghyun/1051.cpp
- 23_11_week5/donghyun/1052.cpp
- 23_11_week5/donghyun/1058.cpp
그래프 문제 생각하기 어렵더라고요 auto 컴파일 옵션 선택하기 귀찮아서 안썻는데 cpp과제도 끝났겠다 모던cpp막 써제끼겠습니다.
물병 문제는 못 풀고 풀이 보고 풀었습니다
> Donghyun 5주차 과제 완

- .gitignore
- 23_12_week1/jahoon/boj1024.cpp
- 23_12_week1/jahoon/boj1174.cpp
- 23_12_week1/jahoon/boj1245.cpp
- 23_12_week1/jahoon/boj13164.cpp
- 23_12_week1/jahoon/boj17175.cpp
-
- [피보나치는 지겨웡~](https://velog.io/@aoleejohn/C-boj-17175-%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98%EB%8A%94-%EC%A7%80%EA%B2%A8%EC%9B%A1)
- [농장 관리](https://velog.io/@aoleejohn/C-boj1245-%EB%86%8D%EC%9E%A5-%EA%B4%80%EB%A6%AC)
- [수열의 합](https://velog.io/@aoleejohn/C-boj1024-%EC%88%98%EC%97%B4%EC%9D%98-%ED%95%A9)
- [행복 유치원](https://velog.io/@aoleejohn/C-boj13164-%ED%96%89%EB%B3%B5-%EC%9C%A0%EC%B9%98%EC%9B%90)
- [줄어드는 수](https://velog.io/@aoleejohn/C-boj1174-%EC%A4%84%EC%96%B4%EB%93%9C%EB%8A%94-%EC%88%98)
> 23_12_week1 자훈 완료

- 23_12_week1/jiyeon/1024.cpp
- 23_12_week1/jiyeon/1174.cpp
- 23_12_week1/jiyeon/1245.cpp
- 23_12_week1/jiyeon/13164.cpp
- 23_12_week1/jiyeon/17175.cpp
- 23_12_week2/jiyeon/20291.cpp
> 23_12_week1 지연 완료

- 23_12_week1/wangon/1024.cpp
- 23_12_week1/wangon/1024.py
- 23_12_week1/wangon/1174.cpp
- 23_12_week1/wangon/1174.py
- 23_12_week1/wangon/1245.cpp
- 23_12_week1/wangon/13164.cpp
- 23_12_week1/wangon/13164.py
- 23_12_week1/wangon/17175.cpp
- 23_12_week1/wangon/17175.py
- 23_12_week2/wangon/2116.cpp
- 23_12_week2/wangon/2116.py
> 23_12_week1 원균 완료

- 23_12_week2/wangon/11497.cpp
- 23_12_week2/wangon/11497.py
- 23_12_week2/wangon/14430.cpp
- 23_12_week2/wangon/14430.py
- 23_12_week2/wangon/20291.cpp
- 23_12_week2/wangon/20291.py
- 23_12_week2/wangon/2116.cpp
- 23_12_week2/wangon/2116.py
- 23_12_week2/wangon/2580.cpp
> 12_week2 원균 완료

- 23_12_week3/wangon/10830.cpp
- 23_12_week3/wangon/1720.cpp
- 23_12_week3/wangon/1793.cpp
- 23_12_week3/wangon/1793.py
- 23_12_week3/wangon/18115.cpp
- 23_12_week3/wangon/18115.py
- 23_12_week3/wangon/2225.cpp
> 23_12_week3 Wangon done

- 23_12_week3/jahoon/boj10830.cpp
- 23_12_week3/jahoon/boj1720.cpp
- 23_12_week3/jahoon/boj1793.cpp
- 23_12_week3/jahoon/boj18115.cpp
- 23_12_week3/jahoon/boj2225.cpp
> 23_12_week3 자훈 완료

- 23_12_week4/jahoon/boj1261.cpp
- 23_12_week4/jahoon/boj14501.cpp
- 23_12_week4/jahoon/boj1707.cpp
- 23_12_week4/jahoon/boj2688.cpp
- 23_12_week4/jahoon/boj7682.cpp
> 자훈 23 12 week4 완료

- 24_01_week1/jahoon/boj11265.cpp
- 24_01_week1/jahoon/boj14716.cpp
- 24_01_week1/jahoon/boj16987.cpp
- 24_01_week1/jahoon/boj2174.cpp
- 24_01_week1/jahoon/boj24480.cpp
> 2024-01-week1 자훈 완료

- 24_01_week1/wangon/16987.cpp
- 24_01_week2/wangon/1477.cpp
- 24_01_week2/wangon/1477.py
- 24_01_week2/wangon/17952.cpp
- 24_01_week2/wangon/17952.py
- 24_01_week2/wangon/5582.cpp
- 24_01_week2/wangon/5582.py
- 24_01_week2/wangon/8394.cpp
- 24_01_week2/wangon/8394.py
- 24_01_week2/wangon/9019.cpp
> 24_week2_Wangon

- 24_01_week2/jiyeon/1477.cpp
- 24_01_week2/jiyeon/17952.cpp
- 24_01_week2/jiyeon/5582.cpp
- 24_01_week2/jiyeon/8394.cpp
- 24_01_week2/jiyeon/9019.cpp
- 5582번 공통 부분 문자열 문제는 인터넷 검색을 참고했습니다. 냅다 비교하면서 풀었더니 시간 초과가 나서 dp로 풀었는데 ... dp 정말 어려버
> 24_01_week2 지연 완료

- 24_01_week3/wangon/14395.cpp
- 24_01_week3/wangon/14465.cpp
- 24_01_week3/wangon/16928.cpp
- 24_01_week3/wangon/25418.cpp
- 24_01_week3/wangon/2698.cpp
> 24_01_week3 Wangon done

- 24_01_week3/jiyeon/14395.cpp
- 24_01_week3/jiyeon/14465.cpp
- 24_01_week3/jiyeon/16928.cpp
- 24_01_week3/jiyeon/25418.cpp
- 24_01_week3/jiyeon/2698.cpp
- 2698번 인접한 비트의 개수 : 인터넷 완전 참고하여 풀었습니다. dp 너무 어려벙
> 24_01_week3 지연 완료

- 24_01_week4/wangon/1004.cpp
- 24_01_week4/wangon/1034.cpp
- 24_01_week4/wangon/1072.cpp
- 24_01_week4/wangon/1107.cpp
- 24_01_week4/wangon/13164.cpp
> 24_01_week4 Wangon done

- 24_01_week3/jahoon/boj14395.cpp
- 24_01_week3/jahoon/boj25418.cpp
- 24_01_week3/jahoon/boj2698.cpp
- 24_01_week4/jahoon/boj1034.cpp
- 24_01_week4/jahoon/boj1072.cpp
- 24_01_week4/jahoon/boj1107.cpp
> 24_01_week4 자훈 완료

- 24_01_week4/jiyeon/1004.cpp
- 24_01_week4/jiyeon/1034.cpp
- 24_01_week4/jiyeon/1038.cpp
- 24_01_week4/jiyeon/1072.cpp
- 24_01_week4/jiyeon/1107.cpp
내일 시간이 안 될 것 같아서 오늘 문제를 2개 풀었습니당. ㅎㅎ !
> 24_01_week4 지연 완료

- 24_01_week5/wangon/1713.cpp
- 24_01_week5/wangon/18405.cpp
- 24_01_week5/wangon/18429.cpp
- 24_01_week5/wangon/19539.cpp
- 24_01_week5/wangon/19637.cpp
> 24_01_week5 Wangon done

- src/AS_24_01_week5/wangon/1713.cpp
- src/AS_24_01_week5/wangon/18405.cpp
- src/AS_24_01_week5/wangon/18429.cpp
- src/AS_24_01_week5/wangon/19539.cpp
- src/AS_24_01_week5/wangon/19637.cpp
> ✨ feat: 01_week5 wangon 추가

- .idea/uiDesigner.xml
- src/AS_24_02_week1/jahoon/boj1000.java
- src/AS_24_02_week1/jahoon/boj1001.java
- src/AS_24_02_week1/jahoon/boj10814.java
- src/AS_24_02_week1/jahoon/boj10926.java
- src/AS_24_02_week1/jahoon/boj11382.java
- src/AS_24_02_week1/jahoon/boj11650.java
- src/AS_24_02_week1/jahoon/boj11651.java
- src/AS_24_02_week1/jahoon/boj1181.java
- src/AS_24_02_week1/jahoon/boj1427.java
- src/AS_24_02_week1/jahoon/boj18870.java
- src/AS_24_02_week1/jahoon/boj25305.java
- src/AS_24_02_week1/jahoon/boj2557.java
- src/AS_24_02_week1/jahoon/boj2587.java
- src/AS_24_02_week1/jahoon/boj2588.java
- src/AS_24_02_week1/jahoon/boj2750.java
- src/AS_24_02_week1/jahoon/boj2751.java
> 24_02_week1 자훈 완료

- .idea/modules.xml
- algorithm_study.iml
- src/AS_24_02_week2/jahoon/boj1018.java
- src/AS_24_02_week2/jahoon/boj10815.java
- src/AS_24_02_week2/jahoon/boj11478.java
- src/AS_24_02_week2/jahoon/boj14425.java
- src/AS_24_02_week2/jahoon/boj15649.java
- src/AS_24_02_week2/jahoon/boj18258.java
- src/AS_24_02_week2/jahoon/boj19532.java
- src/AS_24_02_week2/jahoon/boj2798.java
- src/AS_24_02_week2/jahoon/boj28278.java
- src/AS_24_02_week2/jahoon/boj28279.java
> 24_02_week2 자훈 완료

- src/AS_24_02_week3/jahoon/boj14889.java
- src/AS_24_02_week3/jahoon/boj15650.java
- src/AS_24_02_week3/jahoon/boj1660.java
- src/AS_24_02_week3/jahoon/boj17070.java
- src/AS_24_02_week3/jahoon/boj9663.java
> ✨ [Feature] AS_24_02_week3 자훈 완료

- src/AS_24_02_week4/jahoon/boj10610.java
- src/AS_24_02_week4/jahoon/boj1439.java
- src/AS_24_02_week4/jahoon/boj16926.java
- src/AS_24_02_week4/jahoon/boj20920.java
- src/AS_24_02_week4/jahoon/boj25206.java
> 24_02_week4 자훈 완료

- src/AS_24_03_week1/jahoon/pr250125.java
- src/AS_24_03_week1/jahoon/pr250137.java
- src/AS_24_03_week1/jahoon/pr258712.java
- src/AS_24_03_week1/jahoon/pr50136.java
> AS_24_03_week1 자훈 완료

- src/AS_24_03_week2/jahoon/pr131127.java
- src/AS_24_03_week2/jahoon/pr132265.java
- src/AS_24_03_week2/jahoon/pr135808.java
- src/AS_24_03_week2/jahoon/pr178871.java
- src/AS_24_03_week2/jahoon/pr250121.java
> AS_24_03_week2 자훈 완료

- .gitignore
- src/AS_24_03_week3/jahoon/boj1699.cpp
- src/AS_24_03_week3/jahoon/boj17204.cpp
- src/AS_24_03_week3/jahoon/boj17352.cpp
- src/AS_24_03_week3/jahoon/pr131704.java
- src/AS_24_03_week3/jahoon/pr161989.java
- src/AS_24_03_week3/jahoon/pr60058.java
> ✨  [Feature] 24_03_week3 자훈 완료

- src/AS_24_03_week4/jahoon/boj1138.cpp
- src/AS_24_03_week4/jahoon/boj13172.cpp
- src/AS_24_03_week4/jahoon/boj1342.java
- src/AS_24_03_week4/jahoon/boj1564.cpp
- src/AS_24_03_week4/jahoon/boj19940.cpp
> ✨ [Feature] AS_24_03_week4 Jahoon 완료

- src/AS_24_04_week1/jahoon/boj11268.cpp
- src/AS_24_04_week1/jahoon/boj13414.cpp
- src/AS_24_04_week1/jahoon/boj20164.cpp
- src/AS_24_04_week1/jahoon/boj5972.cpp
> ✨ [Feature] 24_04_week1 jahoon 완료
